### PR TITLE
[IMP] out_of_reality_api: login with faceid

### PR DESCRIPTION
**Pull request by franco-leyes**

### CODE REVIEW

**Comment by out-of-reality** [comment]
[Pull request status dashboard](http://runbot.francoleyes.xyz/out-of-reality/out-of-reality/pull/3)

**Comment by franco-leyes** [comment]
@roboreality r+

**Comment by out-of-reality** [comment]
@franco-leyes you can't review+.

**Comment by francoleyes** [comment]
@roboreality r+

**Pull request closed without merging**
