### PR TITLE
[IMP] clinic_management: add relationships to patient and views

### PR DESCRIPTION
**Pull request by franco-leyes**

### CODE REVIEW

**Comment by out-of-reality** [comment]
[Pull request status dashboard](http://runbot.francoleyes.xyz/out-of-reality/out-of-reality/pull/14)

**Comment by AugustoCacerees** [comment]
@roboreality r+

**Comment by out-of-reality** [comment]
@franco-leyes @AugustoCacerees staging failed: timed out (>60 minutes)

**Comment by francoleyes** [comment]
@roboreality r+

**Comment by out-of-reality** [comment]
This PR is already reviewed, it's in error, you might want to `retry` it instead (if you have already confirmed the error is not legitimate).

**Comment by francoleyes** [comment]
@roboreality retry

**Comment by francoleyes** [comment]
@roboreality r-

**Comment by francoleyes** [comment]
@roboreality r+

**Comment by francoleyes** [comment]
@roboreality r-

**Comment by francoleyes** [comment]
@roboreality r+

**Comment by out-of-reality** [comment]
@franco-leyes @francoleyes unable to stage: merge conflict

**Comment by francoleyes** [comment]
@roboreality r+

**Pull request closed without merging**
